import { TriggerCreate } from "@/components/Modals/Create/Trigger";
import { SearchBar } from "@/components/SearchBar";
import SidebarWithHeader from "@/components/SideBarWithHeader";
import { TableStock } from "@/components/TableStock";
import { Flex, HStack, IconButton, useColorModeValue } from "@chakra-ui/react";
import { Funnel } from "@phosphor-icons/react";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>myStock</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SidebarWithHeader>
          <Flex flexDirection="row" justifyContent="space-between" w="full">
            <SearchBar />

            <HStack mx="2">
              <IconButton
                aria-label="filter"
                icon={<Funnel />}
                textColor={useColorModeValue("black", "white")}
                colorScheme={useColorModeValue("blackAlpha", "whiteAlpha")}
              />
              <TriggerCreate />
            </HStack>
          </Flex>

          <TableStock />
        </SidebarWithHeader>
      </main>
    </>
  );
}
